[package]
name = "travdata-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
atomic-write-file.workspace = true
borsh.workspace = true
clap.workspace = true
csv.workspace = true
ctrlc.workspace = true
gtk.workspace = true
hex.workspace = true
image.workspace = true
lazy-regex.workspace = true
log.workspace = true
lru.workspace = true
pdfium-render.workspace = true
regex.workspace = true
relm4.workspace = true
relm4-components.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
serde_v8.workspace = true
serde_yaml_ng.workspace = true
sha.workspace = true
simple_bar.workspace = true
simplelog.workspace = true
tabula.workspace = true
tempfile.workspace = true
utils.workspace = true
v8.workspace = true
walkdir.workspace = true
xdg.workspace = true
zip.workspace = true

[dev-dependencies]
googletest.workspace = true
test-casing.workspace = true
testutils.workspace = true
