[package]
name = "travdata-pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["std", "serde_derive"] }
serde_json = "1.0.140"
serde_yaml_ng = "0.10.0"
strum = { version = "0.27.1", features = ["derive", "std", "strum_macros"] }
strum_macros = "0.27.1"

[dependencies.generic-pipeline]
package = "travdata-generic-pipeline"
path = "../generic-pipeline"

[dev-dependencies]
googletest = { version = "0.14.0", features = ["anyhow"] }
map-macro = { version = "0.3.0", features = ["hashbrown"] }
test-casing = "0.1.3"
